apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-mysql
  namespace: ums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ums-mysql
  template:
    metadata:
      labels:
        app: ums-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: mysql-storage
          hostPath:
            path: /root/data/mysql
            type: DirectoryOrCreate