#================================================================
# Secret - Stores MySQL credentials securely
#================================================================
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: spring-app
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_NAME: userdb
