#================================================================
# Namespace for Spring Boot Application
#================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: spring-app
  labels:
    app: spring-boot-crud
    environment: production
