apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ums
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: user_management_system

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ums
type: Opaque
stringData:
  DB_HOST: ums-mysql-svc
  DB_PORT: "3306"

---

apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: ums
type: Opaque
stringData:
  BACKEND_HOST: ums-backend-svc
  BACKEND_PORT: "8080"